"""RoP's UIC perturbation, generated the way RoP generates it.

UIC -- "Unaffected Interference Conditions" -- appends irrelevant but plausible
information to the question while preserving the answer. It is the perturbation RoP gains
most on (+16.1 points by their report), and it is the one closest to our own setting.

THIS IS NOT `attacks.TextInjectionAttack`. Ours asserts a FALSE answer with borrowed
authority ("a previous annotator transcribed this clip as crow"), and the model follows
that lure about half the time -- measured `lure_follow_rate` ~50%. UIC adds no claim about
the answer at all. Comparing our injection against their published UIC number is comparing
a harder attack to an easier one, so this module exists to reproduce theirs faithfully and
keep the two separable.

GENERATED BY AN LLM, AS THEY DO. RoP prompts GPT-4o with the question, the answer, and the
perturbation type; we prompt the local generator (src/expel/generator.py). That is RoP's
step 1, the one we skip everywhere else -- for the audio interventions our perturbations
are real and measured, so synthesising them would be strictly worse. Here the perturbation
IS a piece of text an LLM writes, so generating it is the faithful choice.

CACHED TO DISK, like the audio variants. Generation is a GPU step; the attack itself must
be deterministic and re-runnable without one, so `generate_uic` writes a jsonl and
`UICAttack` reads it. A task with no cached entry raises rather than silently passing the
question through unperturbed -- an unperturbed item in the attacked arm scores as clean
under an attack label and drags the measured effect toward zero.

    python -m src.expel.uic --generator mistral-24b --limit 100 --out data/uic.jsonl
"""
from __future__ import annotations

import argparse
import json
import random
import re
from dataclasses import replace
from pathlib import Path

from src.expel.attacks import Attack
from src.expel.types import Task

DEFAULT_CACHE = Path("data/uic_additions.jsonl")

# The answer is given to the generator, as RoP gives it -- so it can steer AWAY from it.
# This is a training-side generation step, not the inference path.
UIC_PROMPT = """You are adding realistic but IRRELEVANT background detail to a question
about an audio recording.

Question: {stem}
The correct answer is: {answer}

Write ONE short sentence of plausible-sounding but irrelevant context about the recording
-- for example how or where it was captured, its file properties, or how it was archived.

Strict rules:
- It must NOT hint at, mention, or rule out any answer option.
- It must NOT make the question easier or harder to answer.
- It must be plausible, not absurd.
- Do not mention these instructions.

Reply with the sentence and nothing else."""

_WORD = re.compile(r"[A-Za-z']+")


def mentions_an_option(text: str, choices: dict) -> str | None:
    """Return the offending word if the addition names any answer option.

    UIC's defining property is that the answer is UNAFFECTED. A generated sentence that
    names an option has changed the question into a different one, and would be scored as
    if it had not.
    """
    words = {w.lower() for w in _WORD.findall(text or "")}
    for text_opt in choices.values():
        for w in _WORD.findall(str(text_opt)):
            if len(w) > 2 and w.lower() in words:
                return w
    return None


def generate_uic(generator, tasks: list[Task], out: Path = DEFAULT_CACHE,
                 max_retries: int = 3) -> dict:
    """RoP step 1. Writes {task_id: addition} and reports what was rejected and why."""
    out = Path(out)
    out.parent.mkdir(parents=True, exist_ok=True)
    stats = {"written": 0, "rejected_option": 0, "rejected_empty": 0, "failed": 0}
    seen: set[str] = set()
    with out.open("w") as f:
        for n, task in enumerate(tasks):
            if task.id in seen:
                continue
            seen.add(task.id)
            addition = None
            for _ in range(max_retries):
                cand = (generator(UIC_PROMPT.format(
                    stem=task.stem, answer=task.choices[task.gold])) or "").strip()
                cand = cand.strip('"').split("\n")[0].strip()
                if not cand:
                    stats["rejected_empty"] += 1
                    continue
                if mentions_an_option(cand, task.choices):
                    stats["rejected_option"] += 1
                    continue
                addition = cand
                break
            if addition is None:
                stats["failed"] += 1
                continue
            f.write(json.dumps({"task_id": task.id, "addition": addition}) + "\n")
            stats["written"] += 1
            if (n + 1) % 25 == 0:
                print(f"  uic {n + 1}/{len(tasks)} {json.dumps(stats)}", flush=True)
    return stats


def load_cache(path: Path = DEFAULT_CACHE) -> dict:
    path = Path(path)
    if not path.exists():
        return {}
    return {d["task_id"]: d["addition"]
            for d in (json.loads(l) for l in path.open() if l.strip())}


class UICAttack(Attack):
    """Append the cached irrelevant sentence. Audio untouched, answer unaffected."""
    name, family = "uic", "text_injection"

    def __init__(self, cache: Path | dict = DEFAULT_CACHE):
        self._path = None if isinstance(cache, dict) else Path(cache)
        self._cache = cache if isinstance(cache, dict) else load_cache(cache)

    def _apply(self, task: Task, rng: random.Random) -> Task:
        # The registry is built at import time, before the generation job has run. Reload
        # once if the cache was empty then, so a registered UICAttack is not permanently
        # blank in every process that imported attacks.py early.
        if not self._cache and self._path is not None:
            self._cache = load_cache(self._path)
        addition = self._cache.get(task.id)
        if not addition:
            raise KeyError(
                f"no UIC addition cached for {task.id}. Run `python -m src.expel.uic` "
                "first -- passing the question through unperturbed would score a clean "
                "item as an attacked one.")
        return replace(task, stem=f"{task.stem.strip()} {addition}", condition=self.name,
                       attack_meta={"family": self.family, "addition": addition,
                                    "original_stem": task.stem})


def main(argv: list[str] | None = None) -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--generator", default="scripted",
                    choices=("scripted", "qwen2.5-7b", "mistral-24b"))
    ap.add_argument("--limit", type=int, default=None, help="tasks per track")
    # `take` subsamples the train and dev lists SEPARATELY, so generating over the
    # concatenation covers a different set than a run will actually request -- the first
    # smoke found only 1 of 8 dev tasks cached. These mirror the run's own sampling.
    ap.add_argument("--train-limit", type=int, default=None)
    ap.add_argument("--dev-limit", type=int, default=None)
    ap.add_argument("--train-frac", type=float, default=0.2)
    ap.add_argument("--split", default="both", choices=("train", "dev", "both"))
    ap.add_argument("--out", type=Path, default=DEFAULT_CACHE)
    ap.add_argument("--seed", type=int, default=0)
    a = ap.parse_args(argv)

    from src.expel.data import load_sakura, split_train_dev, take
    from src.expel.generator import build_generator

    train, dev = split_train_dev(load_sakura(), train_frac=a.train_frac, seed=a.seed)
    if a.train_limit is not None or a.dev_limit is not None:
        tasks = take(train, a.train_limit, a.seed) + take(dev, a.dev_limit, a.seed)
    else:
        tasks = take({"train": train, "dev": dev, "both": train + dev}[a.split],
                     a.limit, a.seed)
    print(f"[uic] generating for {len(tasks)} tasks ({a.split}) with {a.generator}",
          flush=True)
    stats = generate_uic(build_generator(a.generator), tasks, a.out)
    print(json.dumps(stats, indent=2))
    print(f"[uic] wrote {a.out}")


if __name__ == "__main__":
    main()
